let database = [
    {
        id: 1,
        lang1: "готовить",
        lang2: "מבשל",
        lang2_alt: "לְבַשֵׁל",
        trancribe: "мевашель",
        rating: 1,
        part_of_speech: "verb",
        is_exception: 0,
        theme: "house",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    },
    {
        id: 2,
        lang1: "убираться",
        lang2: "מנקה",
        lang2_alt: "לנקות",
        trancribe: "менаке",
        rating: 1,
        part_of_speech: "verb",
        is_exception: 0,
        theme: "house",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    },
    {
        id: 3,
        lang1: "голосовать",
        lang2: "מצביע",
        lang2_alt: "להצביע",
        trancribe: "мацвиа",
        rating: 1,
        part_of_speech: "verb",
        is_exception: "",
        theme: "politics",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    },
    {
        id: 4,
        lang1: "ветер",
        lang2: "רוּחַ",
        lang2_alt: "רוחות",
        trancribe: "руах",
        rating: 1,
        part_of_speech: "noun",
        is_exception: 1,
        theme: "nature",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    },
    {
        id: 5,
        lang1: "солнце",
        lang2: "שמש",
        lang2_alt: "שמשות",
        trancribe: "шемеш",
        rating: 1,
        part_of_speech: "noun",
        is_exception: 1,
        theme: "nature",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    },
    {
        id: 6,
        lang1: "пол",
        lang2: "רִצפָּה",
        lang2_alt: "",
        trancribe: "рицпа",
        rating: 1,
        part_of_speech: "noun",
        is_exception: 0,
        theme: "house",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    },
    {
        id: 7,
        lang1: "вежливый",
        lang2: "מְנוּמָס",
        lang2_alt: "",
        trancribe: "менумас",
        rating: 1,
        part_of_speech: "adjective",
        is_exception: 0,
        theme: "politics",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    },
    {
        id: 8,
        lang1: "президент",
        lang2: "נָשִׂיא",
        lang2_alt: "",
        trancribe: "наси",
        rating: 1,
        part_of_speech: "noun",
        is_exception: 0,
        theme: "politics",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    },
    {
        id: 9,
        lang1: "ленивый",
        lang2: "עָצֵל",
        lang2_alt: "",
        trancribe: "ацель",
        rating: 1,
        part_of_speech: "adjective",
        is_exception: 0,
        theme: "nature",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    },
    {
        id: 10,
        lang1: "лев",
        lang2: "אַריֵה",
        lang2_alt: "",
        trancribe: "арие",
        rating: 1,
        part_of_speech: "noun",
        is_exception: 0,
        theme: "nature",
        vocabulary: 1,
        update_time: "2023-12-10",
        top_rating_counter: 0
    }
]

export default database;